# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1171, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(20, 240, 281, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.google_url_box = QtWidgets.QTextBrowser(self.frame)
        self.google_url_box.setGeometry(QtCore.QRect(10, 250, 251, 91))
        self.google_url_box.setObjectName("google_url_box")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.label.setStyleSheet("font: 12pt \"DejaVu Sans\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 180, 251, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.label_2.setStyleSheet("font: 12pt \"DejaVu Sans\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 64, 17))
        self.label_3.setStyleSheet("font: 12pt \"DejaVu Sans\";")
        self.label_3.setObjectName("label_3")
        self.result_lat = QtWidgets.QLabel(self.frame)
        self.result_lat.setGeometry(QtCore.QRect(10, 80, 261, 17))
        self.result_lat.setText("")
        self.result_lat.setObjectName("result_lat")
        self.result_lon = QtWidgets.QLabel(self.frame)
        self.result_lon.setGeometry(QtCore.QRect(10, 140, 261, 17))
        self.result_lon.setText("")
        self.result_lon.setObjectName("result_lon")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 131, 17))
        self.label_4.setObjectName("label_4")
        self.eastings_label = QtWidgets.QLabel(self.tab)
        self.eastings_label.setGeometry(QtCore.QRect(20, 70, 64, 17))
        self.eastings_label.setObjectName("eastings_label")
        self.eastings_input = QtWidgets.QLineEdit(self.tab)
        self.eastings_input.setGeometry(QtCore.QRect(20, 90, 281, 31))
        self.eastings_input.setObjectName("eastings_input")
        self.northings_label = QtWidgets.QLabel(self.tab)
        self.northings_label.setGeometry(QtCore.QRect(20, 130, 71, 17))
        self.northings_label.setObjectName("northings_label")
        self.northings_input = QtWidgets.QLineEdit(self.tab)
        self.northings_input.setGeometry(QtCore.QRect(20, 150, 281, 31))
        self.northings_input.setObjectName("northings_input")
        self.clear_btn = QtWidgets.QPushButton(self.tab)
        self.clear_btn.setGeometry(QtCore.QRect(1040, 20, 83, 25))
        self.clear_btn.setObjectName("clear_btn")
        self.web_engine = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.web_engine.setGeometry(QtCore.QRect(320, 20, 701, 581))
        self.web_engine.setObjectName("web_engine")
        self.convert_btn = QtWidgets.QPushButton(self.tab)
        self.convert_btn.setGeometry(QtCore.QRect(20, 200, 281, 25))
        self.convert_btn.setObjectName("convert_btn")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.choose_northings = QtWidgets.QComboBox(self.tab_2)
        self.choose_northings.setGeometry(QtCore.QRect(440, 290, 271, 31))
        self.choose_northings.setObjectName("choose_northings")
        self.choose_eastings = QtWidgets.QComboBox(self.tab_2)
        self.choose_eastings.setGeometry(QtCore.QRect(440, 230, 271, 31))
        self.choose_eastings.setObjectName("choose_eastings")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(440, 270, 121, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(440, 210, 101, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(440, 330, 121, 17))
        self.label_8.setObjectName("label_8")
        self.output_filename = QtWidgets.QLineEdit(self.tab_2)
        self.output_filename.setGeometry(QtCore.QRect(440, 360, 271, 31))
        self.output_filename.setObjectName("output_filename")
        self.text_output = QtWidgets.QLabel(self.tab_2)
        self.text_output.setGeometry(QtCore.QRect(440, 490, 271, 41))
        self.text_output.setText("")
        self.text_output.setObjectName("text_output")
        self.outputcsv_btn = QtWidgets.QPushButton(self.tab_2)
        self.outputcsv_btn.setGeometry(QtCore.QRect(440, 400, 271, 81))
        self.outputcsv_btn.setObjectName("outputcsv_btn")
        self.fileopen_btn = QtWidgets.QPushButton(self.tab_2)
        self.fileopen_btn.setGeometry(QtCore.QRect(440, 140, 271, 61))
        self.fileopen_btn.setObjectName("fileopen_btn")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(420, 80, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(1100, 680, 83, 25))
        self.exit_btn.setObjectName("exit_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1223, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eastings and Northing to Lat and Long"))
        self.label.setText(_translate("MainWindow", "Latitude:"))
        self.pushButton.setText(_translate("MainWindow", "Map"))
        self.label_2.setText(_translate("MainWindow", "Longitude:"))
        self.label_3.setText(_translate("MainWindow", "Results:"))
        self.label_4.setText(_translate("MainWindow", "Google Link:"))
        self.eastings_label.setText(_translate("MainWindow", "Eastings:"))
        self.northings_label.setText(_translate("MainWindow", "Northings:"))
        self.clear_btn.setText(_translate("MainWindow", "Reset"))
        self.convert_btn.setText(_translate("MainWindow", "Convert"))
        self.label_5.setText(_translate("MainWindow", "Eastings and Northings Converter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Eastings to Northings"))
        self.label_6.setText(_translate("MainWindow", "Choose Northings:"))
        self.label_7.setText(_translate("MainWindow", "Choose Eastings:"))
        self.label_8.setText(_translate("MainWindow", "Output Filename:"))
        self.outputcsv_btn.setText(_translate("MainWindow", "Output .csv File"))
        self.fileopen_btn.setText(_translate("MainWindow", "Choose .csv File"))
        self.label_9.setText(_translate("MainWindow", "Eastings and Northings CSV Converter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "CSV Eastings Northings add Lat Long"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
from PyQt5 import QtWebEngineWidgets
